# Generated by Django 3.0.3 on 2020-08-25 19:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adminApp', '0003_auto_20200825_1951'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileDetails',
            fields=[
            ],
            options={
                'verbose_name': 'User of Account',
                'verbose_name_plural': 'Users of Account',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('adminApp.profile',),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
    ]
