# Generated by Django 3.0.3 on 2020-08-27 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0004_auto_20200825_2022'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profiledetails',
            options={'verbose_name': 'User Metrics'},
        ),
    ]
