# Generated by Django 3.0.7 on 2020-08-27 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0005_auto_20200827_0327'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profiledetails',
            options={'verbose_name': 'User Metric'},
        ),
    ]
